-- Migration: create guide_sections
-- Backs the public /guide walkthrough page with editable content.
-- Public, read-only via RLS -- content is edited directly through the
-- Supabase Table Editor (service-role access bypasses RLS), not through the app.

CREATE TABLE IF NOT EXISTS guide_sections (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  slug         TEXT        NOT NULL UNIQUE,
  group_label  TEXT        NOT NULL,
  title        TEXT        NOT NULL,
  dek          TEXT        NOT NULL DEFAULT '',
  blocks       JSONB       NOT NULL DEFAULT '[]',
  sort_order   INT         NOT NULL DEFAULT 0,
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_guide_sections_sort ON guide_sections (sort_order);

ALTER TABLE guide_sections ENABLE ROW LEVEL SECURITY;

-- Public, read-only. No write policies on purpose -- edits happen via the
-- Supabase Table Editor (service role), same pattern as platform_admins.
CREATE POLICY "public_read_guide_sections"
  ON guide_sections FOR SELECT
  USING (true);

INSERT INTO guide_sections (slug, group_label, title, dek, blocks, sort_order) VALUES
  ($gsq$sign-in$gsq$, $gsq$Getting started$gsq$, $gsq$Signing in$gsq$, $gsq$You don't need a password — access is by email link.$gsq$, $gsq$[{"type": "ol", "items": ["Go to your admin login page (`/admin/login`), or click the settings icon in the bottom-right corner of your live site.", "Enter the email address your site is registered under.", "Check your inbox for a magic-link email and click it.", "You'll land back in the admin portal, signed in."]}, {"type": "callout", "variant": "tip", "label": "Good to know", "md": "You can only manage the site registered to your email. Signed in with the wrong one? You'll see an access message — sign out and try again with the correct address."}]$gsq$::jsonb, 0),
  ($gsq$dashboard-tour$gsq$, $gsq$Getting started$gsq$, $gsq$The dashboard, at a glance$gsq$, $gsq$Three things orient every visit: the section list on the left, the live preview, and Save.$gsq$, $gsq$[{"type": "ul", "items": ["**Left sidebar** — every editable part of your site. Click a section to open its editor.", "**Show/Hide Preview** — a live preview of your site next to the editor as you work.", "**View Live** — opens your published site in a new tab, exactly as visitors see it.", "**Save** — writes your changes. Nothing is public until you click it."]}, {"type": "text", "md": "The button reads **Saved ✓** once your edits are written — until then, it's safe to keep editing."}]$gsq$::jsonb, 1),
  ($gsq$branding$gsq$, $gsq$Look & feel$gsq$, $gsq$Branding$gsq$, $gsq$Your logo, brand colors, and overall site theme — these apply everywhere at once.$gsq$, $gsq$[{"type": "h3", "text": "Logo"}, {"type": "text", "md": "Upload a PNG or JPG, max 2MB. No logo yet? Your site shows your business initial in a colored badge instead."}, {"type": "h3", "text": "Brand colors"}, {"type": "swatches", "colors": ["#4EBCED", "#464E54", "#45899E"]}, {"type": "ul", "items": ["**Primary** — buttons, links, accents.", "**Secondary** — text, backgrounds, navigation.", "**Accent** — gradients, highlights, hover states."]}, {"type": "text", "md": "Pick with the color swatch or type a hex code directly."}, {"type": "h3", "text": "Site theme"}, {"type": "text", "md": "Sets your layout shape, fonts, and section styling all at once."}, {"type": "pills", "items": [{"label": "Professional", "selected": false}, {"label": "Creative", "selected": false}, {"label": "Wellness", "selected": false}, {"label": "Luxury", "selected": false}, {"label": "Minimalist", "selected": false}, {"label": "Innovative", "selected": false}, {"label": "Restorative", "selected": true}]}, {"type": "callout", "variant": "tip", "label": "Restorative theme only", "md": "Unlocks extended controls: Background, Text, and Muted colors (leave blank to fall back to the default look), plus Display, Body, and Accent fonts chosen from a small curated font list."}]$gsq$::jsonb, 2),
  ($gsq$navigation$gsq$, $gsq$Look & feel$gsq$, $gsq$Navigation$gsq$, $gsq$Control what appears in your header and footer.$gsq$, $gsq$[{"type": "h3", "text": "Header"}, {"type": "toggles", "items": [{"label": "Show logo", "on": true}, {"label": "Show business name", "on": true}, {"label": "Show tagline below logo", "on": false}]}, {"type": "h3", "text": "Secondary button"}, {"type": "text", "md": "An optional second button in the header — useful for a \"Donate\" link or an external booking page — with its own label and URL."}, {"type": "h3", "text": "Footer"}, {"type": "toggles", "items": [{"label": "Show logo", "on": true}, {"label": "Show business name", "on": true}]}, {"type": "text", "md": "Toggles shown in their default position — on when the pill is filled."}]$gsq$::jsonb, 3),
  ($gsq$hero$gsq$, $gsq$Page content$gsq$, $gsq$Hero section$gsq$, $gsq$The first thing visitors see. Edit your headline, subheadline, value statement, and both button labels.$gsq$, $gsq$[{"type": "h3", "text": "Media"}, {"type": "ul", "items": ["**Image or video** background — paste a video URL (YouTube links work) or upload an image.", "**Image ratio** — default (fixed height) or 16:9 widescreen.", "**Background mirror** — a faint, blurred copy of your hero image behind the section for extra depth."]}]$gsq$::jsonb, 4),
  ($gsq$about$gsq$, $gsq$Page content$gsq$, $gsq$About$gsq$, $gsq$Your headline, body copy, mission statement, and button text.$gsq$, $gsq$[{"type": "h3", "text": "Layout"}, {"type": "pills", "items": [{"label": "Standard — centered text", "selected": true}, {"label": "Three-column — image | text | stats", "selected": false}]}, {"type": "text", "md": "Three-column also displays up to three stat callouts (e.g. \"500+ Projects Completed\") once you've filled them in."}, {"type": "toggles", "items": [{"label": "Show media", "desc": "Toggles the About image on/off in the three-column layout.", "on": true}]}]$gsq$::jsonb, 5),
  ($gsq$services$gsq$, $gsq$Page content$gsq$, $gsq$Services$gsq$, $gsq$Up to four services, each with a name, description, benefit line, and button text.$gsq$, $gsq$[{"type": "h3", "text": "Layout"}, {"type": "pills", "items": [{"label": "Cards — 4-column grid", "selected": true}, {"label": "Icon Grid — 2×2 with a side image", "selected": false}]}, {"type": "toggles", "items": [{"label": "Show icon badges", "desc": "Icon Grid layout only.", "on": true}, {"label": "Show CTA buttons", "desc": "Both layouts.", "on": true}]}, {"type": "callout", "variant": "tip", "label": "Per-service URL", "md": "Optional. Set it and the service's button links straight there. Leave it blank and the button scrolls visitors to your contact form instead."}]$gsq$::jsonb, 6),
  ($gsq$benefits$gsq$, $gsq$Page content$gsq$, $gsq$Why Us$gsq$, $gsq$Up to four short benefit callouts — a title and a description each.$gsq$, $gsq$[]$gsq$::jsonb, 7),
  ($gsq$testimonials$gsq$, $gsq$Page content$gsq$, $gsq$Testimonials$gsq$, $gsq$Two testimonial slots: quote, name, and role for each.$gsq$, $gsq$[]$gsq$::jsonb, 8),
  ($gsq$cta$gsq$, $gsq$Page content$gsq$, $gsq$Call to Action$gsq$, $gsq$Edit the CTA banner's headline, body, button text, and urgency line.$gsq$, $gsq$[{"type": "toggles", "items": [{"label": "Use booking / calendar link", "desc": "Button opens a scheduling modal instead of scrolling to the contact form.", "on": false}]}, {"type": "text", "md": "Turn it on and paste your **Booking / Calendar URL** — works with Calendly, GHL Calendar, Cal.com, TidyCal, and similar tools."}]$gsq$::jsonb, 9),
  ($gsq$gallery$gsq$, $gsq$Page content$gsq$, $gsq$Photo Gallery$gsq$, $gsq$Upload up to seven photos. They appear in a grid between your Services and Why Us sections.$gsq$, $gsq$[{"type": "text", "md": "Square or portrait photos look best. Hover a filled slot to replace or remove it."}]$gsq$::jsonb, 10),
  ($gsq$contact$gsq$, $gsq$Leads & contact$gsq$, $gsq$Contact Info$gsq$, $gsq$What shows in your contact section, and where your leads go.$gsq$, $gsq$[{"type": "h3", "text": "Show / hide"}, {"type": "toggles", "items": [{"label": "Phone number", "on": true}, {"label": "Business address", "on": true}, {"label": "Business hours", "on": true}, {"label": "Contact form section", "on": true}, {"label": "Partner & Volunteer options", "desc": "Adds these as extra choices in the form's service dropdown.", "on": false}]}, {"type": "h3", "text": "Lead form source"}, {"type": "text", "md": "By default your site uses the built-in contact form, which emails leads straight to you."}, {"type": "callout", "variant": "new", "label": "New — embed your own form", "md": "Toggle **\"Use an embedded form instead\"** to replace it with a form embedded from GoHighLevel (or another provider):", "items": ["In GoHighLevel, open your form's embed code.", "Copy just the iframe's **src URL** (starts with `https://`) — not the whole embed snippet.", "Paste it into the **Embedded Form URL** field and Save."], "mdAfter": "Your site's contact section now shows your GHL form instead of the built-in one."}, {"type": "text", "md": "Also editable here: contact form title, subtitle, and button text — used by the built-in form only."}]$gsq$::jsonb, 11),
  ($gsq$seo$gsq$, $gsq$Leads & contact$gsq$, $gsq$SEO & Brand$gsq$, $gsq$Your brand tagline, search-listing description, business email, and social links.$gsq$, $gsq$[{"type": "text", "md": "Meta description is what shows in search engine results. Leave a social field blank to hide that icon from your footer."}]$gsq$::jsonb, 12),
  ($gsq$domain$gsq$, $gsq$Going live$gsq$, $gsq$Custom Domain$gsq$, $gsq$Connect your own domain, e.g. `www.yourbusiness.com`.$gsq$, $gsq$[{"type": "ol", "items": ["Log in to your domain registrar — GoDaddy, Namecheap, Cloudflare, or similar.", "Add the DNS record below.", "Come back here, enter your domain (no `https://`), and click Save."]}, {"type": "table", "headers": ["Type", "Name", "Value", "TTL"], "rows": [["CNAME", "www", "myt-client-platform.netlify.app", "3600 (or Auto)"]]}, {"type": "callout", "variant": "tip", "label": "Heads up", "md": "DNS changes can take up to 48 hours to fully propagate — if your domain doesn't connect right away, give it time before troubleshooting."}]$gsq$::jsonb, 13),
  ($gsq$kairos$gsq$, $gsq$Going live$gsq$, $gsq$Kairos Award$gsq$, $gsq$A recognition program that unlocks premium page modules for select clients.$gsq$, $gsq$[{"type": "callout", "variant": "kairos", "label": "If unlocked", "md": "You'll see a gold **Kairos Award** button in your sidebar, with extra page types available — like a Meet the Team / Founder's Story section, or a Portfolio / Case Studies section."}]$gsq$::jsonb, 14),
  ($gsq$publish$gsq$, $gsq$Going live$gsq$, $gsq$Publishing your changes$gsq$, $gsq$Nothing changes on your live site until you click Save.$gsq$, $gsq$[{"type": "text", "md": "Use **Show Preview** to check your edits first, and **View Live** any time to see exactly what visitors see."}]$gsq$::jsonb, 15),
  ($gsq$help$gsq$, $gsq$Going live$gsq$, $gsq$Need help?$gsq$, $gsq$If something isn't working as expected, or you don't have access to the email your site is registered under, contact your mytCreative administrator.$gsq$, $gsq$[]$gsq$::jsonb, 16)
ON CONFLICT (slug) DO UPDATE SET
  group_label = EXCLUDED.group_label,
  title       = EXCLUDED.title,
  dek         = EXCLUDED.dek,
  blocks      = EXCLUDED.blocks,
  sort_order  = EXCLUDED.sort_order,
  updated_at  = now();
